name: keygen

on:
  issues:
    types: [opened,edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/github-script@v6
      with:
        script: |
          const script = require('./keygen.js')
          await script({github, context, core,KEYGEN_JS_CODE:${{secrets.KEYGEN_JS_CODE}}})
